### ISSUE TITLE
nats-bench.go breaks Travis

### ISSUE THREAD

**Issue by drasko** [nats-io/go-nats#249]
The command "go get -v ./..." exited with 2.
https://travis-ci.org/mainflux/mainflux-core/builds/188357908

```
drasko@Lenin:~/go/src/github.com/mainflux/mainflux-core$ go get -v ./...
github.com/nats-io/gnatsd (download)
github.com/nats-io/gnatsd/conf
github.com/nats-io/gnatsd/logger
github.com/nats-io/gnatsd/server/pse
github.com/mainflux/mainflux-core/vendor/github.com/nats-io/go-nats/examples
github.com/nats-io/gnatsd/util
github.com/nats-io/gnatsd/vendor/github.com/nats-io/nuid
github.com/nats-io/gnatsd/vendor/golang.org/x/crypto/blowfish
github.com/mainflux/mainflux-core/vendor/github.com/nats-io/nats/examples
# github.com/mainflux/mainflux-core/vendor/github.com/nats-io/go-nats/examples
vendor/github.com/nats-io/go-nats/examples/nats-bench.go:120: cannot use nc (type *"github.com/mainflux/mainflux-core/vendor/github.com/nats-io/nats".Conn) as type *"github.com/mainflux/mainflux-core/vendor/github.com/nats-io/go-nats".Conn in argument to bench.NewSample
vendor/github.com/nats-io/go-nats/examples/nats-bench.go:139: cannot use nc (type *"github.com/mainflux/mainflux-core/vendor/github.com/nats-io/nats".Conn) as type *"github.com/mainflux/mainflux-core/vendor/github.com/nats-io/go-nats".Conn in argument to bench.NewSample
# github.com/mainflux/mainflux-core/vendor/github.com/nats-io/nats/examples
vendor/github.com/nats-io/nats/examples/nats-bench.go:120: cannot use nc (type *"github.com/mainflux/mainflux-core/vendor/github.com/nats-io/go-nats".Conn) as type *"github.com/mainflux/mainflux-core/vendor/github.com/nats-io/nats".Conn in argument to bench.NewSample
vendor/github.com/nats-io/nats/examples/nats-bench.go:139: cannot use nc (type *"github.com/mainflux/mainflux-core/vendor/github.com/nats-io/go-nats".Conn) as type *"github.com/mainflux/mainflux-core/vendor/github.com/nats-io/nats".Conn in argument to bench.NewSample
github.com/nats-io/gnatsd/vendor/golang.org/x/crypto/bcrypt
github.com/nats-io/gnatsd/server
github.com/nats-io/gnatsd/auth
github.com/nats-io/gnatsd/test
github.com/mainflux/mainflux-core/vendor/github.com/nats-io/go-nats/test
github.com/mainflux/mainflux-core/vendor/github.com/nats-io/nats/test
drasko@Lenin:~/go/src/github.com/mainflux/mainflux-core$ gvim .travis.yml 
```

**Comment by kozlovic** [comment]
@drasko I think this is due to the repo rename (https://github.com/nats-io/go-nats/pull/239). As you can see above you have references to `go-nats` and `nats`. You need to update the mainflux's vendor directory.

**Comment by drasko** [comment]
No, I don't, and `glide.yaml` sees that well:

```
drasko@Lenin:~/go/src/github.com/mainflux/mainflux-core$ cat glide.yaml 
package: github.com/mainflux/mainflux-core
import:
- package: github.com/BurntSushi/toml
  version: ^0.2.0
- package: github.com/cisco/senml
- package: github.com/codegangsta/negroni
  version: ^0.2.0
- package: github.com/fatih/color
  version: ^1.1.0
- package: github.com/go-zoo/bone
  version: ^1.2.0
- package: github.com/nats-io/go-nats
  version: ^1.2.2
- package: github.com/satori/go.uuid
  version: ^1.1.0
- package: github.com/xeipuuv/gojsonschema
- package: gopkg.in/mgo.v2
  subpackages:
  - bson
testImport:
- package: gopkg.in/ory-am/dockertest.v2
  version: ^2.2.3
```

However, I see that you reference `vendor/github.com/nats-io/nats/examples` in NATS 1.2.2, which is your latest official release, and this freaks-out glide.

I think you will need to push new release with these references cleaned ;)
