### ISSUE TITLE
Are different nats.Options.Connect() and nats.Connect(url) ?

### ISSUE THREAD

**Issue by leenux** [nats-io/go-nats#423]
docker-compose file:nats.yml
```
version: '3.5'

networks:
  cherry-network:
    name: cherry-network
    driver: bridge

services:

  nats-0:
    container_name: nats-0
    hostname: nats-0
    image: nats:1.3.0-linux
    networks:
      - cherry-network
    command: -p 4222 -user leenux -pass Synjones123 -cluster nats://nats-0:6222
    ports:
      - 4222:4222

  nats-1:
    container_name: nats-1
    hostname: nats-1
    image: nats:1.3.0-linux
    networks:
      - cherry-network
    command: -p 4222 -user leenux -pass Synjones123 -cluster nats://nats-1:6222 -routes nats://nats-0:6222
    ports:
      - 14222:4222

  nats-2:
    container_name: nats-2
    hostname: nats-2
    image: nats:1.3.0-linux
    networks:
      - cherry-network
    command: -p 4222 -user leenux -pass Synjones123 -cluster nats://nats-2:6222 -routes nats://nats-0:6222
    ports:
      - 24222:4222
```
```
	opts := nats.Options{
		Url:            "nats://localhost:4222,nats://localhost:14222,nats://localhost:24222",
		User:           "leenux",
		Password:       "Synjones123",
		AllowReconnect: true,
		MaxReconnect:   100,
		ReconnectWait:  5 * time.Second,
		Timeout:        1 * time.Second,
	}
	natsSingleton, err := opts.Connect()
	if err != nil {
		zap.L().Error("nats init",
			zap.Any("err", err),
		)
	}
```
result:`nats: no servers available for connection`
```
	natsSingleton, err := nats.Connect("nats://localhost:4222,nats://localhost:14222,nats://localhost:24222",
		nats.ReconnectWait(time.Second*5),
		nats.UserInfo("leenux", "Synjones123"),
		nats.MaxReconnects(100),
		nats.Timeout(time.Second), )
	if err != nil {
		zap.L().Error("nats init",
			zap.Any("err", err),
		)
	}
```
result is ok and no errors
